name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  uploadrelease:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        name: Get current daytime
        run: echo "RELEASEDATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        name: Getcsvdata
        run: ./getdata.sh
        working-directory: githubaction
      - uses: actions/checkout@v4
        name: makerelease
        run: |
          echo "リリース名:$NOW"
          git tag $RELEASEDATE
          git push origin $RELEASEDATE
          gh release -p create $RELEASEDATE
          gh release upload $RELEASEDATE githubaction/test3.csv 
          gh release edit $RELEASEDATE --prerelease=false --latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

