name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  uploadrelease:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::ggplot2
      - name: Get current daytime
        uses: actions/checkout@v4
      - run: echo "RELEASEDATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: make graph
        run: |
           ./getdata.sh
           Rscript makegraph.R test3-100.csv plot2.png
        working-directory: githubaction
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "リリース名:$RELEASEDATE"
          git tag $RELEASEDATE
          git push origin $RELEASEDATE
          gh release create $RELEASEDATE --prerelease --notes automake
      - name: upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $RELEASEDATE githubaction/test3-100.csv 
          gh release edit $RELEASEDATE --prerelease=false --latest

