name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  uploadrelease:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::ggplot2
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Get current daytime
        uses: actions/checkout@v4
      - run: echo "RELEASEDATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: make graph
        run: |
           ./getdata.sh
           Rscript makegraph.R test3-100.csv plot2.png
           cp plot2.png ../Pages/data
           cp plot2.png ../Pages
           echo "hello" > ../Pages/index2.html
           ls -alh .
           ls -alh ../Pages
           ls -alh ../Pages/data
        working-directory: githubaction
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "リリース名:$RELEASEDATE"
          git tag $RELEASEDATE
          git push origin $RELEASEDATE
          gh release create $RELEASEDATE --prerelease --notes automake
      - name: upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $RELEASEDATE githubaction/test3-100.csv 
          gh release edit $RELEASEDATE --prerelease=false --latest

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'Pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
