name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  HelloWorld:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: step1
        working-directory: githubaction
      - run: ./getdata.sh

